adding functionality to load credentials from secrets for scanner chart
giantswarm/aqua-app pull request #56
Opened 2021-03-16 15:06 UTC by KoppulaRajender

2021-03-17 10:11 UTC, webwurst approved these changes
Thank you!

2021-03-18 11:40 UTC, ced0ps requested changes

2021-03-18 11:40 UTC, ced0ps commented on helm/aqua-app-scanner/values.yaml
> +  passwordKey: "" #password key defined in secret
```suggestion
  passwordKey: ""  #password key defined in secret
```
Double white space due to linting rules

2021-03-18 12:11 UTC, webwurst approved these changes

2021-03-19 12:57 UTC, ced0ps approved these changes

2021-03-19 12:58 UTC, merged